<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VisualNotes.Core\VisualNotes.Core.csproj" />
    <ProjectReference Include="..\VisualNotes.Infrastructure\VisualNotes.Infrastructure.csproj" />
  </ItemGroup>
</Project>
